### ISSUE TITLE
How can we install Dragonegg on Mac?

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/sulong#116]
We can install GCC 4.8 via Homebrew

```
brew tap homebrew/versions
brew install gcc48 --with-fortran
```

But this doesn't seem to include GCC plugin headers and so building Dragonegg fails.

**Comment by bjfish** [comment]
I was checking what's available in the package managers: There is `dragonegg-3.3` available in macports. Homebrew also has `llvm33` and above available (but not `llvm32` version used by `dragonegg-3.2`).

**Comment by chrisseaton** [comment]
I don't think getting LLVM is the issue - we download a binary of that as part of the Dragonegg installation process.

**Comment by chrisseaton** [comment]
Sorry, `gcc48` does actually include the plugin headers - in `lib/gcc/4.8/gcc/x86_64-apple-darwin15.3.0/4.8.5/plugin/include/`.

My problem now is the `libiberty` header. There isn't a package for this as you're supposed to vendor it.

I downloaded the GCC 4.8 source and added the `include` dir (which has `libiberty.h`) as an `-I` on line 85 of the Dragonegg `Makefile`. That gets me a little further, but then I get stuck at:

```
$ GCC=gcc-4.8 CXX=g++-4.8 CC=gcc-4.8 LLVM_CONFIG=../../llvm/bin/llvm-config make
gcc-4.8 --version > /dev/null
../../llvm/bin/llvm-config --version > /dev/null
Compiling Aliasing.cpp
g++-4.8 -c -DTARGET_NAME=\"x86_64-apple-darwin15.3.0\" -I/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/include/x86 -I/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/include/darwin  -I/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/llvm/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -MD -MP -DIN_GCC -DLLVM_VERSION=\"3.2svn\" -DGCC_MAJOR=4 -DGCC_MINOR=8 -DGCC_MICRO=5 -I/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/include -isystem/usr/local/Cellar/gcc48/4.8.5/lib/gcc/4.8/gcc/x86_64-apple-darwin15.3.0/4.8.5/plugin/include -I/Users/chrisseaton/Downloads/gcc-4.8.0/include -Wall -Wextra -fvisibility=hidden -I/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/llvm/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual /Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/src/Aliasing.cpp
In file included from /usr/local/Cellar/gcc48/4.8.5/lib/gcc/4.8/gcc/x86_64-apple-darwin15.3.0/4.8.5/plugin/include/tree.h:27:0,
                 from /Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/src/Aliasing.cpp:48:
/usr/local/Cellar/gcc48/4.8.5/lib/gcc/4.8/gcc/x86_64-apple-darwin15.3.0/4.8.5/plugin/include/vec.h:230:3: error: template with C linkage
   template <typename, typename, typename> friend struct vec;
   ^
```

So `Aliasing.cpp:48` includes `tree.h`, `tree.h:27` includes `vec.h`, which includes templates, but `Aliasing.cpp` is doing the include in an `extern "C"`, so that doesn't work.

I then tried setting `-DENABLE_BUILD_WITH_CXX`, which seems to turn off the `extern`, but then I get a bunch of errors like this:

```
/Users/chrisseaton/Documents/graal/sulong-workspace/sulong/projects/com.oracle.truffle.llvm.tools/tools/dragonegg/dragonegg-3.2.src/src/Backend.cpp:899:23: error: 'struct cgraph_node' has no member named 'decl'
       target = fnode->decl;
                       ^
```

The whole thing just makes me think Dragonegg isn't as compatible with GCC 4.8 as we thought. @mrigger where did you get the info it worked with GCC 4.8?

Maybe we should go back and keep trying to install GCC 4.6 on the Mac.

**Comment by chrisseaton** [comment]
GCC 4.6 can be installed by `brew edit gcc46`, replace `p0` with https://gist.githubusercontent.com/chrisseaton/7008085997269e3478e1/raw/46bff773d37914d6e66d0d8e1cab0d50d77e7280/patch-10.10.diff (`sha256 "51814a0d79a9f21344c76f2d4235b59d9a4bc1601117e8ca5bfabdb82305aad0"`).

**Comment by chrisseaton** [comment]
Trying to get that integrated into Homebrew in https://github.com/Homebrew/homebrew-versions/issues/515

**Comment by mickjordan** [comment]
For the record, gcc46 (and many other packages) can also be installed via MacPorts, https://www.macports.org/. MacPorts itself comes with a standard Mac "pkg" installer and has very good documentation. Once installed you can install gcc4.6 by "sudo port install gcc46". MacPorts uses /opt/local for all installs and uses rather specific names, e.g. /opt/local/bin/gcc-mp-4.6. If you want generic names in, say, /usr/local, you have to make the links yourselgf. However, I have found it sufficient to set SULONG_GCC, etc, to the MacPorts location.
